version: "3.5"

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/database:/data/db
    networks:
      - api-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  api_1: &api
    container_name: api_1
    hostname: api_1
    build: .
    ports:
      - "8000:8000"
    networks:
      - api-net
    environment:
      - DATABASE_NAME=api_1
      - VIZINHOS=api_3
      - MONGO_URI=mongodb://admin:admin@mongodb:27017

  api_2:
    <<: *api
    container_name: api_2
    hostname: api_2
    ports:
      - "8001:8000"
    environment:
      - DATABASE_NAME=api_2
      - VIZINHOS=api_1,api_3
      - MONGO_URI=mongodb://admin:admin@mongodb:27017

  api_3:
    <<: *api
    container_name: api_3
    hostname: api_3
    ports:
      - "8002:8000"
    environment:
      - DATABASE_NAME=api_3
      - VIZINHOS=api_1,api_4
      - MONGO_URI=mongodb://admin:admin@mongodb:27017

  api_4:
    <<: *api
    container_name: api_4
    hostname: api_4
    ports:
      - "8003:8000"
    environment:
      - DATABASE_NAME=api_4
      - VIZINHOS=api_1,api_3,api_5
      - MONGO_URI=mongodb://admin:admin@mongodb:27017

  api_5:
    <<: *api
    container_name: api_5
    hostname: api_5
    ports:
      - "8004:8000"
    environment:
      - DATABASE_NAME=api_5
      - VIZINHOS=api_2
      - MONGO_URI=mongodb://admin:admin@mongodb:27017

networks:
  api-net:
    driver: bridge
